---

- name: copy 90proxy
  copy:
    src: "{{ apt_proxy_file }}"
    dest: /etc/apt/apt.conf.d/90proxy
    owner: root
    group: root
    mode: 0660 

- name: do a full upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  register: system_upgraded
