up () {
  local d=""
  local limit="$1"

  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
    limit=1
  fi

  for ((i=1;i<=limit;i++)); do
    d="../$d"
  done

  if ! cd "$d"; then
    echo "Konnte keine $limit Verzeichnisse nach oben gehen";
  fi
}

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias la='exa -al --color=always --group-directories-first'
alias lt='exa -aT --color=always --group-directories-first'
alias ll='exa -l --color=always --group-directories-first'
alias l='ls -CF'

alias aptup='sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y'  
alias aptupd='sudo apt update -y'
alias aptupg='sudo apt full-upgrade -y'
alias aptrm='sudo apt remove'
alias aptin='sudo apt install'

alias systemctl='sudo systemctl'

alias wgu='sudo systemctl start wg-quick@wg0'
alias wgd='sudo systemctl stop wg-quick@wg0'
alias apb='ansible-playbook'
alias cheat='~/bin/cheat.sh'
alias top='bpytop'
alias htop='bpytop'
alias ..='up 1'
alias ...='up 2'
alias ....='up 3'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

alias df='df -h'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
