---

- name: update all, except critical
  hosts: all:!critical
  remote_user: "{{ the_remote_user }}"
  become: "{{ do_become }}"
  roles:
    - full_upgrade
    - bash_settings
    - standard_apps_common

